language: cpp

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make

os:
    - linux
    - osx

branches:
    only:
        -master

notifications:
    email:
        on_failure: always
        on_success: change
