language: cpp

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make

script:
    - ctest -V

os:
    - linux
    - osx

notifications:
    email:
        on_failure: always
        on_success: change
