language: cpp

compiler:
    - clang
    - gcc

before_script:
    - pip install --user cpp-coveralls

script:
    - mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=coverage && make
    - ctest -V

after_success:
    - coveralls --exclude src/utils --exclude tests --exclude scripts --gcov-options '\-lp'

os:
    - linux
    - osx

notifications:
    email:
        on_failure: always
        on_success: change
